const poisonsData = [
  {
    poison: "Basic Poison",
    type: "Injury",
    rarity: "Common",
    cost: "25gp",
    savingthrow: "DC 10 Constitution",
    damage: "1d4 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "Basic poison is a general term for the most commonplace poisons that are made typically with poisonous plants, such as grey jasmine, or various toxic alchemical reagents. A creature subjected to this poison must make a DC 10 Constitution saving throw or take 1d4 poison damage.",
  },
  {
    poison: "Serpent Venom",
    type: "Injury",
    rarity: "Common",
    cost: "50gp",
    savingthrow: "DC 10 Constitution",
    damage: "1d6 poison ",
    inflicts: "-",
    duration: "-",
    effect:
      "Serpent venom is a type of venom that is extracted and bottled from a variety of venomous snakes. A creature subjected to this poison must succeed on a DC 10 Constitution saving throw, taking 1d6 poison damage on a failed save, or half as much damage on a successful one.",
  },
  {
    poison: "Seizeleg Poison",
    type: "Injury",
    rarity: "Common",
    cost: "50gp",
    savingthrow: "DC 10 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "10 minutes",
    effect:
      "Dart frog venom is a type of venom that is extracted from poison dart frogs or other forms of frogs that secrete a venomous outer layer. A creature subjected to this poison must make a DC 10 Constitution saving throw or become Poisoned for 10 minutes.",
  },
  {
    poison: "Dart Frog Venom",
    type: "Contact",
    rarity: "Common",
    cost: "75gp",
    savingthrow: "DC 12 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "8 hours",
    effect:
      "Potent Crimsonvine is crushed and powdered Crimsonvine, a weaker poisonous vine that grows in jungles and forested areas. A creature subjected to this poison must make a DC 12 Constitution saving throw or become Poisoned for 8 hours.",
  },
  {
    poison: "Silent Sickness",
    type: "Ingested",
    rarity: "Common",
    cost: "20gp",
    savingthrow: "DC 11 Constitution",
    damage: "1d4 poison",
    inflicts: "Prone",
    duration: "-",
    effect:
      "Seizeleg poison is a thick, blackish red liquid made from crushed jumping beans and bullette tendons. A creature subjected to this poison must make a DC 11 Constitution saving throw or take 1d4 poison damage and be knocked prone as their muscles temporarily seize up.",
  },
  {
    poison: "Potent Crimsonvine",
    type: "Ingested",
    rarity: "Common",
    cost: "25gp",
    savingthrow: "DC 10 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "8 hours",
    effect:
      "Silent Sickness is a clear, flavorless, and odorless poison made from distilled and refined Juniker berries. A creature subjected to this poison must make a DC 10 Constitution saving throw or become Poisoned for the next 8 hours, where the creature becomes violently sick.",
  },
  {
    poison: "Purple Jasmine Extract",
    type: "Injury",
    rarity: "Uncommon",
    cost: "75gp",
    savingthrow: "DC 12 Constitution",
    damage: "1d6 poison ",
    inflicts: "-",
    duration: "-",
    effect:
      "This extract is the refined residue and chlorophyll of purple jasmine, a naturally toxic fern. A creature subjected to this poison must succeed on a DC 12 Constitution saving throw or take 1d6 poison damage.",
  },
  {
    poison: "Drow Poison",
    type: "Injury",
    rarity: "Uncommon",
    cost: "100 gp",
    savingthrow: "DC 13 Constitution",
    damage: "-",
    inflicts: "Poisoned / Unconscious",
    duration: "1 hour",
    effect:
      "This poison is typically made only by the drow, created from refined and crushed Drowvine that only grows in places far removed from sunlight. A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or be Poisoned for 1 hour. If the saving throw fails by 5 or more, the creature is also Unconscious while Poisoned in this way. The creature wakes up if it takes damage or if another creature takes an action to shake it awake.",
  },
  {
    poison: "Nightlock Extract",
    type: "Injury",
    rarity: "Uncommon",
    cost: "150 gp",
    savingthrow: "DC 14 Constitution",
    damage: "-",
    inflicts: "-",
    duration: "1 minute",
    effect:
      "Nightlock Extract are crushed, boiled, and treated Nightlock berries that become a brackish purple liquid with an extremely sharp scent. A creature subjected to this poison must succeed on a DC 14 Constitution saving throw or become Poisoned for 1 minute. A creature Poisoned in this way can remake the saving throw at the end of their turn, ending the Poisoned effect upon success. Once a creature succeeds on this saving throw or the initial saving throw, they are immune to the effects of Nightlock Extract for 24 hours.",
  },
  {
    poison: "Blackwillow Poison",
    type: "Injury",
    rarity: "Uncommon",
    cost: "250 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "1 hour",
    effect:
      "Blackwillow poison is a type of poison that is refined and treated from the dreaded Blackwillows which typically grow in swampy and necrotic environments. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become Poisoned for 1 hour. While Poisoned in this way, they are also vulnerable to Necrotic damage. Once a creature succeeds on their saving throw against Blackwillow Poison, they are immune to its effects for 24 hours.",
  },
  {
    poison: "Crawler Mucus",
    type: "Contact",
    rarity: "Uncommon",
    cost: "100 gp",
    savingthrow: "DC 13 Constitution",
    damage: "-",
    inflicts: "Poisoned/ Paralyze",
    duration: "1 minute",
    effect:
      "This poison is the thick mucus found within the maw and coating the tentacles of a carrion crawler. A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or be Poisoned for 1 minute. The Poisoned creature is Paralyzed. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
  },
  {
    poison: "Husk",
    type: "Contact",
    rarity: "Uncommon",
    cost: "100 gp",
    savingthrow: "DC 12 Constitution",
    damage: "1d6 necrotic each turn",
    inflicts: "Poisoned",
    duration: "1 minute",
    effect:
      "Made from a combination of crushed Deathsprigs and sapping salts refined into a thick, gritty liquid, Husk is a poison that drains the moisture out the affected creature rapidly until they are nothing more than a dried husk. A creature subjected to this poison must succeed on a DC 12 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature takes 1d6 necrotic damage at the start of each of their turns. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
  },
  {
    poison: "Giant Jellyfish Toxin",
    type: "Contact",
    rarity: "Uncommon",
    cost: "125 gp",
    savingthrow: "DC 12 Constitution",
    damage: "-",
    inflicts: "Poisoned/ Paralyze",
    duration: "1 minute",
    effect:
      "Extracted from the tentacles and membrane of giant jellyfish, giant jellyfish toxin is a potent neurotoxin. A creature subjected to this poison must succeed on a DC 12 Constitution saving throw or be Poisoned for 1 minute. While Poisoned in this way, the creature is also Paralyzed. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. Giant Jellyfish Toxin does not wash off while submerged, and can be used with full effectiveness when underwater.",
  },
  {
    poison: "Mycanoid Bane",
    type: "Contact",
    rarity: "Uncommon",
    cost: "150 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "-",
    duration: "-",
    effect:
      "Less of a poison and more of a parasite, Mycanoid Bane is a ½ inch to 3 inch long black seed that softly wriggles with grasping vines, engineered and created from the Mycanoid Bane plant by an ancient Mind Flayer for the purposes of subduing and killing Mycanoids and fungi with ease. If Mycanoid Bane comes into contact with a Mycanoid or any type of fungus, the creature must succeed on a DC 15 Constitution saving throw or have the seed latch onto them and begin to infect them. While affected by Mycanoid Bane, the Mycanoid/Fungus gains Vulnerability to all damage types until the Mycanoid Bane seed is removed as an Action with a Strength check of 15. Mycanoid Bane only affects Mycanoids and Fungi, but is commonly used as a base for other parasitic-based inhaled poisons.",
  },
  {
    poison: "Death's Sweat",
    type: "Contact",
    rarity: "Uncommon",
    cost: "150 gp",
    savingthrow: "DC 10 Constitution",
    damage: "-",
    inflicts: "Paralyzed",
    duration: "1 round",
    effect:
      "Death’s Sweat is a thick paste that is made from cut, dried, ground, and mixed Deathweed which is found deep within the thick detritus of rotted vegetable matter. A creature subjected to this poison must succeed on a DC 10 Constitution saving throw or become Paralyzed until the end of their next turn. Once a creature has become paralyzed by Death’s Sweat, they are immune to its effects for 24 hours.",
  },
  {
    poison: "Truth Serum",
    type: "Ingested",
    rarity: "Uncommon",
    cost: "75 gp",
    savingthrow: "DC 11 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "1 hour",
    effect:
      "Made from the blood of Sprites and refined Dayblooms, truth serum is a poison most often used in interrogations. A creature subjected to this poison must succeed on a DC 11 Constitution saving throw or become Poisoned for 1 hour. While Poisoned in this way, the creature can’t knowingly speak a lie, as if under the Effect of a Zone of Truth spell.",
  },
  {
    poison: "Assassin's Blood",
    type: "Ingested",
    rarity: "Uncommon",
    cost: "75 gp",
    savingthrow: "DC 10 Constitution",
    damage: "1d12 poison",
    inflicts: "Poisoned",
    duration: "24 hours",
    effect:
      "Commonly used by assassins and spies, assassin’s blood is a reddish liquid of alchemical makeup and has a faintly bitter aftertaste. A creature subjected to this poison must make a DC 10 Constitution saving throw. On a failed save, it takes 1d12 poison damage and is Poisoned for 24 hours. On a successful save, the creature takes half damage and isn’t Poisoned.",
  },
  {
    poison: "Pale Tincture",
    type: "Ingested",
    rarity: "Uncommon",
    cost: "100 gp",
    savingthrow: "DC 16 Constitution",
    damage: "1d6 poison ",
    inflicts: "Poisoned",
    duration: "Special",
    effect:
      "Pale tincture is a milky white liquid that glows very faintly when stirred, made from the leaves of the midnight berries and various nightshades. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or take 1d6 poison damage and become Poisoned. The Poisoned creature must repeat the saving throw every 24 hours, taking 1d6 poison damage on a failed save. Until this poison ends, the damage the poison deals can’t be healed by any means. After seven successful saving throws, the poisoned condition ends and the creature can heal normally.",
  },
  {
    poison: "Medusa Extract",
    type: "Ingested",
    rarity: "Uncommon",
    cost: "200 gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "Paralyzed",
    duration: "10 minutes",
    effect:
      "Medusa Extract is a cut, treated, and boiled Medusa’s Bellflower that creates a stony blue syrup that tastes and smells incredibly sweet, to the point where it is almost sickening. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or become Paralyzed for 10 minutes.",
  },
  {
    poison: "Turtleweed Powder",
    type: "Ingested",
    rarity: "Uncommon",
    cost: "200 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "1 exhaustion",
    duration: "8 hours",
    effect:
      "Turtleweed Powder is the refined, treated, and powdered form of Turtleweed that has been distilled and enhanced. A creature subjected to this poison must succeed on a Constitution saving throw of 15 or become poisoned for 8 hours and suffer a point of exhaustion. While poisoned in this way, the creature is unconscious. Upon a success, the creature instead takes 1 point of exhaustion and is not poisoned.",
  },
  {
    poison: "Malice",
    type: "Inhaled",
    rarity: "Uncommon",
    cost: "100 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "Poisoned / Blinded",
    duration: "1 hour",
    effect:
      "Malice is the bottled vapors that follow the banishment or killing of a demon of the abyss, in combination with chimney mushroom spores. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become Poisoned for 1 hour. While Poisoned in this way, the creature is also Blinded.",
  },
  {
    poison: "Lunispores",
    type: "Inhaled",
    rarity: "Uncommon",
    cost: "150 gp",
    savingthrow: "DC 14 Constitution",
    damage: "-",
    inflicts: "Blinded",
    duration: "1 minute",
    effect:
      "Lunispores is a combination of dried Lunaris flower petals and buds as well as Mycanoid Bane, who have been bonded together to create parasitic spores attracted to the eyes. Lunispores causes the sclera and iris to fill with bright pale light, and is especially effective against creatures who have eyes that are adapted to darkness, as the unnatural light is much brighter. A creature who is subjected to this poison must succeed on a DC 14 Constitution saving throw or become Blinded for 1 minute. A creature with the Darkvision trait has disadvantage on their saving throw. The creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success.",
  },
  {
    poison: "Bloomshroom Spores",
    type: "Inhaled",
    rarity: "Uncommon",
    cost: "150 gp",
    savingthrow: "DC 14 Constitution",
    damage: "2d6 poison",
    inflicts: "Poisoned",
    duration: "1 minute",
    effect:
      "Bloomshroom Spores are bottled concentrated spores of the Bloomshroom. A creature subjected to this poison must succeed on a DC 14 Constitution saving throw. Upon failure, the creature takes 2d6 poison damage and becomes Poisoned for 1 minute, where the creature can repeat the saving throw at the end of each of its turns, ending the effect on itself on a success. Upon success, the creature only takes half damage and is not Poisoned.",
  },
  {
    poison: "Flaxen Poppy Pollen",
    type: "Inhaled",
    rarity: "Uncommon",
    cost: "250gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "1 exhaustion",
    duration: "10 minutes",
    effect:
      "Flaxen Poppy Pollen is the bottled pollen of the dreaded Flaxen Poppy, and is known to induce feelings of extreme drowsiness. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or suffer 1 point of exhaustion. A creature who fails this saving throw by 5 or more falls Unconscious for 10 minutes. The creature wakes up if it takes damage or if another creature takes an action to shake them awake.",
  },
  {
    poison: "Black Jasmine Extract",
    type: "Injury",
    rarity: "Rare",
    cost: "125 gp",
    savingthrow: "DC 14 Constitution",
    damage: "1d8 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "This extract is the refined residue and chlorophyll of black jasmine, a naturally toxic fern that is more potent than purple jasmine. A creature subjected to this poison must succeed on a DC 14 Constitution saving throw or take 1d8 poison damage.",
  },
  {
    poison: "Brightbane",
    type: "Injury",
    rarity: "Rare",
    cost: "200 gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "1 minute",
    effect:
      "This poison is made of a modified Mycanoid Bane along with dried and crushed lightroot to create a parasitic poison that takes over the bloodstream and causes it to glow. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or become Poisoned for 1 minute. While Poisoned, the creature visibly glows and emits bright light out to 10 feet in every direction. Because of this the creature cannot benefit from invisibility and the creature suffers disadvantage on all Dexterity (Stealth) checks made to hide.",
  },
  {
    poison: "Seabane",
    type: "Injury",
    rarity: "Rare",
    cost: "200 gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "10 minutes",
    effect:
      "This poison is made of modified kellerfins and boiled sharkblood that has steeped in aboleth mucus for several days to become a deadly toxin that specifically targets creatures who breathe underwater. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or become Poisoned for 10 minutes. If a creature can breathe underwater via gills or other natural means, Seabane causes this organ to swell and cease to function, where the creature will lose the ability to breathe underwater until they are no longer Poisoned. This poison does not wash away while submerged and is fully effective when used underwater.",
  },
  {
    poison: "Deathshroom Extract",
    type: "Injury",
    rarity: "Rare",
    cost: "250 gp",
    savingthrow: "DC 16 Constitution",
    damage: "3d12 poison",
    inflicts: "Poisoned",
    duration: "1 hour",
    effect:
      "This poison is the combination of the sweet-smelling, but incredibly deadly, Deathshroom spores and meat which have been distilled and concentrated into a viscous purple liquid with streaks of neon green within. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or take 3d12 poison damage and become Poisoned for 1 hour. Upon success, the creature only takes half damage and is not Poisoned.",
  },
  {
    poison: "Ghastgrip",
    type: "Injury",
    rarity: "Rare",
    cost: "300 gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "10 minutes",
    effect:
      "Ghastgrip is a tar-like poison made of powdered ghast bones, ground wight flesh, modified Mycanoid Bane, and bonded together with Blackwillow sap to create a poison that when introduced to the body, sucks away all positive energy and incoming life force from the creature. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or become Poisoned for 10 minutes. While Poisoned in this way, the creature cannot regain any hit points.",
  },
  {
    poison: "Wyvern Poison",
    type: "Injury",
    rarity: "Rare",
    cost: "500 gp",
    savingthrow: "DC 15 Constitution",
    damage: "7d6 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "This poison is harvested from the deadly stingers of Wyverns. A creature subjected to this poison must make a DC 15 Constitution saving throw, taking 7d6 poison damage on a failed save, or half as much damage on a successful one.",
  },
  {
    poison: "Burning Blood",
    type: "Injury",
    rarity: "Rare",
    cost: "500 gp",
    savingthrow: "DC 15 Constitution",
    damage: "2d6 fire each turn",
    inflicts: "Poisoned",
    duration: "1 minute",
    effect:
      "Burning Blood is a poison often refined and found within desert climates as it is made from komodo dragon saliva, fireblooms, and fireseeds which when combined and let fester for seven days becomes a poison that causes the blood to combust throughout the body. A creature subjected to this poison must make a DC 15 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature takes 2d6 fire damage at the start of each of their turns.",
  },
  {
    poison: "Mageshackle",
    type: "Injury",
    rarity: "Rare",
    cost: "600 gp",
    savingthrow: "DC 16 Constitution",
    damage: "-",
    inflicts: "Poisoned",
    duration: "1 minute",
    effect:
      "Used by assassins that often hunt spellcasters or mages, Mageshackle is made from rotted Elderberries and poisonous herbs. A creature subjected to this poison must succeed on a DC 16 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature has disadvantage on all Constitution saving throws made to maintain concentration on spells.",
  },
  {
    poison: "Oil of Taggit",
    type: "Contact",
    rarity: "Rare",
    cost: "500 gp",
    savingthrow: "DC 13 Constitution",
    damage: "-",
    inflicts: "Poisoned / Unconscious",
    duration: "24 hours",
    effect:
      "Oil of Taggit is a potent toxin that is made from the refined excretions and meat of the Taggit root found deep within the earth and within the feywild. A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or become Poisoned for 24 hours. While Poisoned, the creature is Unconscious. The creature wakes up if it takes damage.",
  },
  {
    poison: "Weeping Cactus Poison",
    type: "Contact",
    rarity: "Rare",
    cost: "750 gp",
    savingthrow: "DC 16 Constitution",
    damage: "3d6 poison",
    inflicts: "Poisoned",
    duration: "1 hour",
    effect:
      "This poison is the secretion of the weeping cactus found within desert environments. A creature subjected to this poison must make a DC 16 Constitution saving throw or take 3d6 poison damage and become poisoned for 1 hour, taking half damage and avoiding the poisoned condition upon success.",
  },
  {
    poison: "Midnight Tears",
    type: "Ingested",
    rarity: "Rare",
    cost: "400 gp",
    savingthrow: "DC 17 Constitution",
    damage: "9d6 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "Created from a ripe midnight berry that is only found within high reaching mountains, and withers away only a few hours after midnight, Midnight Tears is an incredibly potent and dangerous poison that is odorless, colorless, and tasteless. A creature that ingests this poison suffers no effect until the stroke of midnight. If the poison has not been neutralized before then, the creature must succeed on a DC 17 Constitution saving throw, taking 9d6 poison damage on a failed save, or half as much damage on a successful one.",
  },
  {
    poison: "Torpor",
    type: "Ingested",
    rarity: "Rare",
    cost: "300 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "Poisoned / Incapacitated",
    duration: "4d6 hours",
    effect:
      "Torpor is a poison that is a combination of herbs that all share heavy sedative properties, refined and steeped over months to become incredibly potent. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become Poisoned for 4d6 hours. While Poisoned, the creature is Incapacitated.",
  },
  {
    poison: "Burnt Othur Fumes",
    type: "Inhaled",
    rarity: "Rare",
    cost: "150 gp",
    savingthrow: "DC 13 Constitution",
    damage: "3d6 poison each turn",
    inflicts: "",
    duration: "3 successful saves",
    effect:
      "This poison is a powder distilled from numerous different poisonous plants that have been ground together and distilled so it remains inert until it is burnt. With a combination of a dried and modified firebloom powder, the powder ignites when exposed to air. A creature subjected to this poison must succeed on a DC 13 Constitution saving throw or take 3d6 poison damage, and must repeat the saving throw at the start of each of its turns. On each successive failed save, the character takes 1d6 poison damage. After three successful saves, the poison ends.",
  },
  {
    poison: "Essence of Ether",
    type: "Inhaled",
    rarity: "Rare",
    cost: "150 gp",
    savingthrow: "DC 15 Constitution",
    damage: "-",
    inflicts: "Poisoned / Unconscious",
    duration: "8 hours",
    effect:
      "This poison is made up of dried elderberry leaves that have been imbued with the essence of the ethereal plane, which when inhaled, overloads the unconscious with psychic energy causing near-instant unconsciousness. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become Poisoned for 8 hours. While Poisoned, the creature is Unconscious. The creature wakes up if it takes damage or if another creature takes an action to shake it awake.",
  },
  {
    poison: "Hillblossom’s Breath",
    type: "Inhaled",
    rarity: "Rare",
    cost: "450 gp",
    savingthrow: "DC 15 Constitution",
    damage: "",
    inflicts: "Int 6",
    duration: "1 minute",
    effect:
      "This poison is made from the boiled and treated center of the Hillblossom, in combination with poisonous plants to create a mind-numbing gas. A creature subjected to this poison must succeed on a DC 15 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature’s Intelligence score is reduced to 6.",
  },
  {
    poison: "Death Jasmine Extract",
    type: "Injury",
    rarity: "Very Rare",
    cost: "600 gp",
    savingthrow: "DC 18 Constitution",
    damage: "4d8 + 8 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "This extract is the refined residue and chlorophyll of death jasmine, a naturally toxic fern that is influenced by necrotic energies and the most potent of the grey jasmine family. A creature subjected to this poison must succeed on a DC 18 Constitution saving throw or take 4d8+8 poison damage.",
  },
  {
    poison: "Purple Worm Poison",
    type: "Injury",
    rarity: "Very Rare",
    cost: "1,000 gp",
    savingthrow: "DC 19 Constitution",
    damage: "12d6 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "This poison is the deadly venom found within the stingers of purple worms. A creature subjected to this poison must make a DC 19 Constitution saving throw, taking 12d6 poison damage on a failed save, or half as much damage on a successful one.",
  },
  {
    poison: "Efreeti Bane",
    type: "Contact",
    rarity: "Very Rare",
    cost: "1,250 gp",
    savingthrow: "DC 18 Constitution",
    damage: "Special",
    inflicts: "-",
    duration: "-",
    effect:
      "Used often in revolts and uprisings against magocracies or political coups against mage figures, Magus Tears is made from dried elderberry leaves, cut up and dried Spellbane creepers, and this is infused with the raw energy of the weave and the fresh blood of a sorcerer. A creature subjected to this poison must make a DC 18 Constitution saving throw, or expend their highest level spell slot and take force damage equal to an amount of d8s equal to the level of the spell lost, taking only half the damage they would've taken if they had lost their highest level spell slot upon success. If a creature fails this saving throw by 5 or more, all creatures within 20 feet of affected creature must succeed on a DC 18 Constitution saving throw or take the same amount of force damage the affected creature took, halved on success.",
  },
  {
    poison: "Death Shivers",
    type: "Contact",
    rarity: "Very Rare",
    cost: "1,250 gp",
    savingthrow: "DC 19 Constitution",
    damage: "-",
    inflicts: "Vulnerable to charm",
    duration: "8 hours",
    effect:
      "Known as one of the most inhumane nonlethal poisons due to its ethical implications, Lover's Blindness is made from crushed and squeezed Lover's Warmth in combination with Incubus or Succubus blood and mermaid tears. A creature subjected to this poison must succeed on a DC 19 Constitution saving throw or be affected by the poison for the next 8 hours. While affected by the poison, there are no visible symptoms; however if the creature is forced to make a saving throw against an effect that would Charm them, they automatically fail their saving throw and the poison fades from their system.",
  },
  {
    poison: "Kraken’s Ire",
    type: "Contact",
    rarity: "Very Rare",
    cost: "1,250 gp",
    savingthrow: "DC 17 Constitution",
    damage: "-",
    inflicts: "Poisoned / Exhaustion",
    duration: "1 minute",
    effect:
      "This poison is the bottled fumes and smokes of burnt concentrated flaxen poppy pollen and enchanted turtleweed. A creature who is subjected to this poison must succeed on a DC17 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature must succeed on a DC 17 Constitution saving throw at the start of each of their turns or gain 1 point of exhaustion. A creature can only gain 5 levels of exhaustion from this poison.",
  },
  {
    poison: "Magus Tears",
    type: "Ingested",
    rarity: "Very Rare",
    cost: "500 gp",
    savingthrow: "DC 17 Constitution",
    damage: "-",
    inflicts: "Poisoned / Vulnerable to fire",
    duration: "1 minute",
    effect:
      "This poison is an incredibly potent thick paste composed of fireblooms dipped in magma, crushed flameseeds, modified Mycanoid Bane, and bonded with Salamander blood to make a parasitic poison that heightens and amplifies the intensity of flames. A creature subjected to this poison must succeed on a DC 17 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature has vulnerability to fire damage. Once a creature has succeeded on their saving throw to resist the effects of Efreeti Bane, they are immune to the effects of the poison for 24 hours.",
  },
  {
    poison: "Lover’s Blindness",
    type: "Ingested",
    rarity: "Very Rare",
    cost: "750 gp",
    savingthrow: "DC 17 Constitution",
    damage: "-",
    inflicts: "Poisoned / Vulnerable to cold",
    duration: "1 minute",
    effect:
      "This poison is a freezing paste composed of shiverpetals, ground winter wolf teeth, modified Mycanoid Bane, and bonded with yeti blood to make a parasitic poison that amplifies and exacerbates chilling effects to sub zero temperatures. A creature subjected to this poison must succeed on a DC 17 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature has vulnerability to cold damage. Once a creature has succeeded on their saving throw to resist the effects of Death Shivers, they are immune to the effects of the poison for 24 hours.",
  },
  {
    poison: "Dragonturtle’s Slumber",
    type: "Inhaled",
    rarity: "Very Rare",
    cost: "950 gp",
    savingthrow: "DC 17 Constitution",
    damage: "-",
    inflicts: "Poisoned / Vulnerable to lightning",
    duration: "1 minute",
    effect:
      "This poison is a buzzing brackish paste composed of crushed aboleth bones, enchanted kellerfins, modified Mycanoid Bane, and bonded with kraken blood to make a parasitic poison that acts as a conduit and amplifier for electrical energy. A creature subjected to this poison must succeed on a DC 17 Constitution saving throw or become Poisoned for 1 minute. While Poisoned in this way, the creature has vulnerability to lightning damage. Once a creature has succeeded on their saving throw to resist the effects of Kraken's Ire, they are immune to the effects of the poison for 24 hours.",
  },
  {
    poison: "Death Lotus Poison",
    type: "Ingested",
    rarity: "Legendary",
    cost: "4,500 gp",
    savingthrow: "DC 21 Constitution",
    damage: "9d10 poison",
    inflicts: "-",
    duration: "-",
    effect:
      "The Death Lotus Poison is one of the rarest and most sought after poisons in the material plane. Made from the fabled death lotus, rumored only to grow in desecrated land in the shadowfell where a lich has been recently slain, the death lotus poison is a deep midnight purple poison that burns the nostrils and causes intense sickness and visions of mortality from just its fumes. A creature subjected to this poison must succeed on a DC 21 Constitution saving throw or be reduced to 0 hit points, taking 9d10 poison damage upon success. If a creature is larger than the size category Large or has a Constitution score of 20 or higher, they automatically succeed on their saving throw made to resist this poison. Once a creature has succeeded on their saving throw to resist the Death Lotus Poison, they are immune to its effects for seven days.",
  },
];
export default poisonsData;
