const armorData = [
  {
    armor: "Padded",
    cost: "5 gp",
    armorclass: "11 + Dex modifier",
    strength: "—",
    stealth: "Disadvantage",
    weight: "8 lb.",
    armorrange: "-",
    damreduction: "-",
  },
  {
    armor: "Leather",
    cost: "10 gp",
    armorclass: "11 + Dex modifier",
    strength: "—",
    stealth: "—",
    weight: "10 lb.",
    armorrange: "-",
    damreduction: "-",
  },
  {
    armor: "Studded leather",
    cost: "45 gp",
    armorclass: "12 + Dex modifier",
    strength: "—",
    stealth: "—",
    weight: "13 lb.",
    armorrange: "-",
    damreduction: "-",
  },
  {
    armor: "Hide",
    cost: "10 gp",
    armorclass: "12 + Dex modifier (max 2)",
    strength: "—",
    stealth: "—",
    weight: "12 lb.",
    armorrange: "13-14",
    damreduction: "-2",
  },
  {
    armor: "Chain shirt",
    cost: "50 gp",
    armorclass: "13 + Dex modifier (max 2)",
    strength: "—",
    stealth: "—",
    weight: "20 lb.",
    armorrange: "14-16",
    damreduction: "-3",
  },
  {
    armor: "Scale mail",
    cost: "50 gp",
    armorclass: "14 + Dex modifier (max 2)",
    strength: "—",
    stealth: "Disadvantage",
    weight: "45 lb.",
    armorrange: "15-18",
    damreduction: "-4",
  },
  {
    armor: "Breastplate",
    cost: "400 gp",
    armorclass: "14 + Dex modifier (max 2)",
    strength: "—",
    stealth: "—",
    weight: "20 lb.",
    armorrange: "15-18",
    damreduction: "-4",
  },
  {
    armor: "Half plate",
    cost: "750 gp",
    armorclass: "15 + Dex modifier (max 2)",
    strength: "—",
    stealth: "Disadvantage",
    weight: "40 lb.",
    armorrange: "16-20",
    damreduction: "-5",
  },
  {
    armor: "Ring mail",
    cost: "30 gp",
    armorclass: "14",
    strength: "—",
    stealth: "Disadvantage",
    weight: "40 lb.",
    armorrange: "15-18",
    damreduction: "-4",
  },
  {
    armor: "Chain mail",
    cost: "75 gp",
    armorclass: "16",
    strength: "Str 13",
    stealth: "Disadvantage",
    weight: "55 lb.",
    armorrange: "17-22",
    damreduction: "-6",
  },
  {
    armor: "Splint",
    cost: "200 gp",
    armorclass: "17",
    strength: "Str 15",
    stealth: "Disadvantage",
    weight: "60 lb.",
    armorrange: "18-24",
    damreduction: "-7",
  },
  {
    armor: "Plate",
    cost: "1,500 gp",
    armorclass: "18",
    strength: "Str 15",
    stealth: "Disadvantage",
    weight: "65 lb.",
    armorrange: "19-26",
    damreduction: "-8",
  },
];

export default armorData;
